server {
	listen 80;
	server_name nsmun.duckdns.org;

	if ($host = nsmun.duckdns.org) {
		return 301 https://$host$request_uri;
	}
}

server {
	listen 443 ssl;
	server_name nsmun.duckdns.org;

	location / {
		proxy_pass http://nsmun.duckdns.org:5000/;
	}

	ssl_certificate /etc/letsencrypt/live/nsmun.duckdns.org/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/nsmun.duckdns.org/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/nsmun.duckdns.org/chain.pem;
}
